### ISSUE TITLE
constraint =0 fails

### ISSUE THREAD

**Issue by UniWarwickGrahamWilmott** [ndunand/moodle-qtype_multinumerical#17] opened 2023-10-16 11:06 UTC
When a question has a constraint which equals zero, the condition always fails.

Eg, "X-1=0" will fail, but "x=1" and "x+1=2" both work.

We are using version 2023010901 on Moodle 4.1.6, and these questions were working as expected on the previous version.

**Comment by NicoAlexH** [comment] 2024-01-30 11:37
Hello, thanks for reporting !

I ran some tests trying to reproduce this issue, including creating a question as follows : 

![image](https://github.com/ndunand/moodle-qtype_multinumerical/assets/19607263/46ff2591-b94c-46b2-a606-aff1b22762f3)

The zero equality seems to be working as expected, or am I missing something ?  
I am using version 2023010901 of the plugin on Moodle 4.2.4. 

Have a nice day, 
Nicolas

**Comment by UniWarwickGrahamWilmott** [comment] 2024-01-30 12:04
Hi,

We are using this version:
![image](https://github.com/ndunand/moodle-qtype_multinumerical/assets/138119379/772a9771-b85d-47b7-9bb5-bef6a8f32d9a)

When I create a question as follows:
![image](https://github.com/ndunand/moodle-qtype_multinumerical/assets/138119379/d0e45b77-2531-4d86-a4c8-84056340d3e2)

When I put an answer of "1" in, I get 
![image](https://github.com/ndunand/moodle-qtype_multinumerical/assets/138119379/ad0b7168-f951-4d2f-9a51-9f24ccbba066)

![image](https://github.com/ndunand/moodle-qtype_multinumerical/assets/138119379/6c5cc51a-e869-454f-b329-ca735f6a13ca)


However, making a question "x=1":
![image](https://github.com/ndunand/moodle-qtype_multinumerical/assets/138119379/1e53c64e-aaca-444b-b3d4-f0cc6a68c093)

works fine:
![image](https://github.com/ndunand/moodle-qtype_multinumerical/assets/138119379/6b847cd2-d2c4-4332-86d1-7f623d20e0ab)

**Comment by UniWarwickGrahamWilmott** [comment] 2024-01-30 12:05
Happy to provide other versions / info as needed.

**Comment by UniWarwickGrahamWilmott** [comment] 2024-01-30 14:06
Yep - we are currently using PHP 7.4.

**Comment by NicoAlexH** [comment] 2024-01-30 16:34
I just checked with @ndunand and sadly we don't have any more testing servers with Moodle 4.1 and PHP 7.4, nor the time to recreate one I am sorry... The issue might be due to the code using new features introduced by PHP 8.1 in the method check_condition() in question.php:120, but I cannot say for sure. 
I think if you run the unit tests (or manual tests) on your side with debugging enabled, you will find what is causing it and apply a temporary patch, otherwise you might want to use an older working version of the plugin.
I am closing this issue as it -seemingly- doesn't happen with supported PHP versions, but feel free to reopen it if needed.

Have a nice day, 
Nicolas

**Closed by NicoAlexH** 2024-01-30 16:34 UTC
